//QUESTION
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
export const SET_EXAM_DATA = 'SET_EXAM_DATA';
export const UNSET_EXAM_DATA = 'UNSET_EXAM_DATA';
export const SET_EXAM_STATE = 'SET_EXAM_STATE';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_QUESTION_IS_AUTHENTICATED = "SET_QUESTION_IS_AUTHENTICATED";
export const UNSET_QUESTION_IS_AUTHENTICATED = "UNSET_QUESTION_IS_AUTHENTICATED";
export const SET_VCHANGE = "SET_VCHANGE";
export const UNSET_VCHANGE = "UNSET_VCHANGE";
export const SET_TIME_SPENT_ON_EACH_QUESTION = "SET_TIME_SPENT_ON_EACH_QUESTION";
export const SET_TIME_LEFT_PER_SECTION = "SET_TIME_LEFT_PER_SECTION ";
export const SET_PROGRESS = "SET_PROGRESS";


//UPLOADER
export const UPLOADER = 'UPLOADER';
export const CREATOR = 'CREATOR';
export const UPLOADER_GET_COURSES = 'UPLOADER_GET_COURSES';
export const UPLOADER_GET_COURSE_SUBJECTS = 'UPLOADER_GET_COURSE_SUBJECTS';
export const UPLOADER_GET_SUBJECT_TOPICS = 'UPLOADER_GET_SUBJECT_TOPICS';
export const UPLOADER_GET_TOPIC_CHAPTERS = 'UPLOADER_GET_TOPIC_CHAPTERS';
export const SET_UPLOADER_IS_AUTHENTICATED = "SET_UPLOADER_IS_AUTHENTICATED";
export const UNSET_UPLOADER_IS_AUTHENTICATED = "UNSET_UPLOADER_IS_AUTHENTICATED";

//SELECTED LEVEL
export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';
export const SET_CURRENT_LEVEL_CHILD = 'SET_CURRENT_LEVEL_CHILD';
export const LOGIN = "LOGIN" ;
export const GET_LEVEL_MEDIA = "GET_LEVEL_MEDIA";
export const SET_SELECT_LEVEL_IS_AUTHENTICATED = "SET_SELECT_LEVEL_IS_AUTHENTICATED";
export const UNSET_SELECT_LEVEL_IS_AUTHENTICATED = "UNSET_SELECT_LEVEL_IS_AUTHENTICATED";
export const GET_PACKAGEDETAIL = "GET_PACKAGEDETAIL";


//Course Builder


export const SET_MODAL_OPEN="SET_MODAL_OPEN";
export const SET_MODAL_CLOSE="SET_MODAL_CLOSE";
export const SET_IS_FETCHING="SET_IS_FETCHING";

export const SET_SELECTED_ID = "SET_SELECTED_ID";


export const GET_COURSES = "GET_COURSES";
export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_TOPIC = "GET_TOPICS";
export const GET_CHAPTERS = "GET_CHAPTERS";

export const GET_COURSE_VIDEO_LIST = "GET_COURSE_VIDEO_LIST";
export const GET_SUBJECT_VIDEO_LIST = "GET_SUBJECT_VIDEO_LIST";
export const GET_TOPIC_VIDEO_LIST = "GET_TOPIC_VIDEO_LIST";
export const GET_CHAPTER_VIDEO_LIST = "GET_CHAPTER_VIDEO_LIST";

export const SET_IS_FETCHING_COURSES = "SET_IS_FETCHING_COURSES";
export const SET_IS_FETCHING_SUBJECTS = "SET_IS_FETCHING_SUBJECTS";
export const SET_IS_FETCHING_TOPICS = "SET_IS_FETCHING_TOPICS";
export const SET_IS_FETCHING_CHAPTERS = "SET_IS_FETCHING_CHAPTERS";

export const GET_COURSE_QUIZ_LIST = "GET_COURSE_QUIZ_LIST";
export const GET_SUBJECT_QUIZ_LIST = "GET_SUBJECT_QUIZ_LIST";
export const GET_TOPIC_QUIZ_LIST = "GET_TOPIC_QUIZ_LIST";
export const GET_CHAPTER_QUIZ_LIST = "GET_CHAPTER_QUIZ_LIST";








